config/routes.rb
Rails.application.routes.draw do
## 会員用
# URL /customers/sign_in ...
  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

## 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :end_user do
    ## ゲストログイン用
    post 'end_users/guest_sign_in',to: 'public/sessions#new_guest'
  end


## 会員側ルート設定
  scope module: :public do
    ## homes
    root "homes#top"
    ## sweets_revues
    resources :sweets_revues do
      ## post_comments
      # sweets_revuesに対してコメントされるので親子関係になる
      # ネストしたURLを作成することでparams[:sweets_revue_id]でPostImageのidが取得できるようになる
      resources :post_comments, only: [:create, :destroy]
      ## favorites
      # resource : 単数形にすると、/:idがURLに含まれなくなります
      # 1人のユーザーは1つの投稿に対して1回しかいいねできない」という仕様の為idを含めなくても関連する他のモデルのidから特定できる
      resource :favorites, only: [:create, :destroy]
    end
    ## end_users
    get 'end_users/my_page' => 'end_users#mypage', as: 'mypage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'end_users/infomation/:id/edit' => 'end_users#edit', as: 'edit_infomation'
    # patch 'end_users/infomation/:id' => 'end_users#update', as: "update_end_user"
    patch 'end_users/information' => "end_users#update"
    # 退会確認画面
    get 'end_users/confirm'
    # 論理削除用のルーティング
    patch 'end_users/:id/withdraw' => 'end_users#withdraw', as: 'withdraw_end_user'
    resources :end_users, only: [:index, :show] do
      ##relationships
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      # いいね一覧用のルーティング
      # member doを使うとユーザーidが含まれているurlになる
      member do
        get :favorites
      end

    end

  end


 ##管理者側ルート設定
  namespace :admin do
    root "homes#top"
    resources :sweets_revues, only: [:show, :update, :index]
    patch 'sweets_revues/:id/stoppage' => 'sweets_revues#stoppage', as: 'stoppage_sweets_revue'
    resources :end_users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :update, :destroy]
    resources :tags, only: [:index, :edit, :create, :update, :destroy]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :sweets_revues, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルの登録に成功しました"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      flash[:notice] = "ジャンルの登録に失敗しました"
      render :index
    end
  end

  def destroy
    @genre = Genre.find(params[:id])
    @genre.destroy
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/index.html.erb
<div class="container">
  <%= render "admin/shared/error_messages", resource: @genre %>

  <div class="row justify-content-center mb-5">
    <h4><span class="title">ジャンル一覧・追加</span></h4>
  </div>

  <div class="row justify-content-center">
    <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
      <div class="d-flex">
        <div class="class mr-2"><%= f.text_field :name, placeholder: "ジャンル名" %></div>
        <div><%= f.submit "新規登録", class: "btn btn-outline-success" %></div>
      </div>
    <% end %>
  </div>

<div class="row justify-content-center mb-5">
  <div class="form-box col-6 mt-5">
    <!--タグ検索-->
    <% @genres.each do |genre| %>
      <!--[:tag_ids]だけだと、他の[tag_ids]と区別がつかないので、[:tag_ids, t.name]としている-->
      <div class="form-check-label m-2">
        <%= genre.name %>
        <%= link_to "削除する", admin_genre_path(genre.id), method: :delete, class: "btn btn-outline-danger", data: { confirm: "本当に削除しますか？" } %>
      </div>
    <% end %>
  </div>
</div>