config/routes.rb
Rails.application.routes.draw do
## 会員用
# URL /customers/sign_in ...
  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

## 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :end_user do
    ## ゲストログイン用
    post 'end_users/guest_sign_in',to: 'public/sessions#new_guest'
  end


## 会員側ルート設定
  scope module: :public do
    ## homes
    root "homes#top"
    ## sweets_revues
    resources :sweets_revues do
      ## post_comments
      # sweets_revuesに対してコメントされるので親子関係になる
      # ネストしたURLを作成することでparams[:sweets_revue_id]でPostImageのidが取得できるようになる
      resources :post_comments, only: [:create, :destroy]
      ## favorites
      # resource : 単数形にすると、/:idがURLに含まれなくなります
      # 1人のユーザーは1つの投稿に対して1回しかいいねできない」という仕様の為idを含めなくても関連する他のモデルのidから特定できる
      resource :favorites, only: [:create, :destroy]
    end
    ## end_users
    get 'end_users/my_page' => 'end_users#mypage', as: 'mypage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'end_users/infomation/:id/edit' => 'end_users#edit', as: 'edit_infomation'
    # patch 'end_users/infomation/:id' => 'end_users#update', as: "update_end_user"
    patch 'end_users/information' => "end_users#update"
    # 退会確認画面
    get 'end_users/confirm'
    # 論理削除用のルーティング
    patch 'end_users/:id/withdraw' => 'end_users#withdraw', as: 'withdraw_end_user'
    resources :end_users, only: [:index, :show] do
      ##relationships
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      # いいね一覧用のルーティング
      # member doを使うとユーザーidが含まれているurlになる
      member do
        get :favorites
      end

    end

  end


 ##管理者側ルート設定
  namespace :admin do
    root "homes#top"
    resources :sweets_revues, only: [:show, :update, :index]
    patch 'sweets_revues/:id/stoppage' => 'sweets_revues#stoppage', as: 'stoppage_sweets_revue'
    resources :end_users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :update, :destroy]
    resources :tags, only: [:index, :edit, :create, :update, :destroy]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :revue_tag_relations, dependent: :destroy
  # 中間テーブルを介してSweetsRevueテーブルへの関連付け
  has_many :sweets_revues, through: :revue_tag_relations

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
    before_action :authenticate_admin!

  def index
    @tags = Tag.all
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:notice] = "タグの登録に成功しました"
      redirect_to admin_tags_path
    else
      @tags = Tag.all
      flash[:notice] = "タグの登録に失敗しました"
      render :index
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
      if @tag.update(tag_params)
        flash[:notice] = "タグの更新に成功しました"
        redirect_to admin_tags_path
      else
        flash[:notice] = "タグ更新に失敗しました"
        render :edit
      end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    flash[:notice] = "タグの削除に成功しました"
    redirect_to admin_tags_path
  end


  private

  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/edit.html.erb
<div class="container">
  <%= render "admin/shared/error_messages", resource: @tag %>

  <div class="row justify-content-center mb-2">
    <h4><span class="title">タグ編集</span></h4>
  </div>

  <div class="row justify-content-center">
    <%= form_with model: @tag, url: admin_tag_path, method: :patch do |f| %>
    <div class="d-flex">
      <div class="class mr-2"><%= f.text_field :name, placeholder: "タグ名" %></div>
      <div><%= f.submit "変更を保存", class: "btn btn-outline-success" %></div>
    </div>
    <% end %>
  </div>



</did>

app/views/admin/tags/index.html.erb
<div class="container">
  <%= render "admin/shared/error_messages", resource: @tag %>

  <div class="row justify-content-center mb-5">
    <h4><span class="title">タグ一覧・追加</span></h4>
  </div>

  <div class="row justify-content-center">
    <%= form_with model: @tag, url: admin_tags_path, method: :post do |f| %>
    <div class="d-flex">
      <div class="class mr-2"><%= f.text_field :name, placeholder: "タグ名" %></div>
      <div><%= f.submit "新規登録", class: "btn btn-outline-success" %></div>
    </div>
    <% end %>
  </div>

  <div class="row justify-content-center mb-5">
    <div class="form-box col-8 mt-5 saiz: 10">
      <!--タグ検索-->
      <% @tags.each do |tag| %>
        <!--[:tag_ids]だけだと、他の[tag_ids]と区別がつかないので、[:tag_ids, t.name]としている-->
        <div class="form-check-label">
          <%= link_to edit_admin_tag_path(tag.id), class: "text-dark" do %>
            <%= tag.name %>
          <% end %>
          <%= link_to admin_tag_path(tag.id), class: "text-danger", method: :delete, data: { confirm: "本当に削除しますか？" } do %>
             ×
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>