config/routes.rb
Rails.application.routes.draw do
## 会員用
# URL /customers/sign_in ...
  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

## 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :end_user do
    ## ゲストログイン用
    post 'end_users/guest_sign_in',to: 'public/sessions#new_guest'
  end


## 会員側ルート設定
  scope module: :public do
    ## homes
    root "homes#top"
    ## sweets_revues
    resources :sweets_revues do
      ## post_comments
      # sweets_revuesに対してコメントされるので親子関係になる
      # ネストしたURLを作成することでparams[:sweets_revue_id]でPostImageのidが取得できるようになる
      resources :post_comments, only: [:create, :destroy]
      ## favorites
      # resource : 単数形にすると、/:idがURLに含まれなくなります
      # 1人のユーザーは1つの投稿に対して1回しかいいねできない」という仕様の為idを含めなくても関連する他のモデルのidから特定できる
      resource :favorites, only: [:create, :destroy]
    end
    ## end_users
    get 'end_users/my_page' => 'end_users#mypage', as: 'mypage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'end_users/infomation/:id/edit' => 'end_users#edit', as: 'edit_infomation'
    # patch 'end_users/infomation/:id' => 'end_users#update', as: "update_end_user"
    patch 'end_users/information' => "end_users#update"
    # 退会確認画面
    get 'end_users/confirm'
    # 論理削除用のルーティング
    patch 'end_users/:id/withdraw' => 'end_users#withdraw', as: 'withdraw_end_user'
    resources :end_users, only: [:index, :show] do
      ##relationships
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      # いいね一覧用のルーティング
      # member doを使うとユーザーidが含まれているurlになる
      member do
        get :favorites
      end

    end

  end


 ##管理者側ルート設定
  namespace :admin do
    root "homes#top"
    resources :sweets_revues, only: [:show, :update, :index]
    patch 'sweets_revues/:id/stoppage' => 'sweets_revues#stoppage', as: 'stoppage_sweets_revue'
    resources :end_users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :update, :destroy]
    resources :tags, only: [:index, :edit, :create, :update, :destroy]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/end_user.rb
class EndUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:nickname]  #ログイン認証のキーをニックネームへ
  ## アソシエーション
  has_many :sweets_revues, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  # 退会済みのユーザーがログインできない制約
  # is_deleteがfalseならtrueを返す
  def active_for_authentication?
    super && (is_deleted == false)
  end
  # 退会済みユーザーを表示する
  def show
    @end_user = EndUser.with_deleted.find(:id)
  end

  ## 画像投稿出来るようにする
  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_profile_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end


  ## フォローをした
  # relationships = 分かりやすいように名前をつけただけ
  # class_name: "Relationship"でRelationshipテーブルを参照
  # foreign_key(外侮キー)で参照するカラムを指定
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  ## フォローされた
  # reverse_of_relationships = 分かりやすいように名前をつけただけ
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  ## 一覧画面で使う
  #  フォロー・フォロワーの一覧画面で、user.followersという記述でフォロワーを表示したいので、
  #  throughでスルーするテーブル、sourceで参照するカラムを指定。
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  # フォローしたときの処理の定義
  def follow(end_user_id)
    relationships.create(followed_id: end_user_id)
  end
  # フォローを外すときの処理の定義
  def unfollow(end_user_id)
    relationships.find_by(followed_id: end_user_id).destroy
  end
  # フォローしているか判定
  def following?(end_user)
    followings.include?(end_user)
  end

  ## バリデーション
  validates :name, presence: true
  validates :nickname, presence: true, uniqueness: true
  validates :introduction, length: { maximum: 100 }

end

app/controllers/admin/end_users_controller.rb
class Admin::EndUsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @end_users = EndUser.all.page(params[:page]).per(15)
  end

  def show
    @end_user = EndUser.find(params[:id])
    @sweets_revues = @end_user.sweets_revues.all.page(params[:page]).per(5).order(created_at: :desc)
  end

  def edit
    @end_user = EndUser.find(params[:id])
  end

  def update
    @end_user = EndUser.find(params[:id])
   if @end_user.update(end_user_params)
      redirect_to admin_end_users_path
   else
      render :edit
   end
  end

  private

  def end_user_params
    params.require(:end_user).permit(
      :name, :nickname, :introduction, :is_deleted, :profile_image
    )
  end


end

app/helpers/admin/end_users_helper.rb
module Admin::EndUsersHelper
end

app/views/admin/end_users/_admin_end_user_info.html.erb
<div class = "icon-circle">
  <%= image_tag end_user.get_profile_image(120,120) %>
</div>
<div>
  <%= link_to edit_admin_end_user_path(end_user) do %>
    <i class="fas fa-cog"></i>編集
  <% end %>
</div>

<div class = "infomationbox">
  <div class="my_intro_box">
	  <div class="intro_label">名前</div>
	  <div class="intro_field_name"><%= end_user.name %></div>
	  <div class="intro_label">ニックネーム</div>
	  <div class="intro_field_name"><%= end_user.nickname %></div>
	  <div class="intro_label">introduction</div>
	  <div class="intro_field"><%= end_user.introduction %></div>
  </div>
  <div class="my_count">
    <%= end_user.sweets_revues.count %>投稿
  </div>
  <div class="my_count">
      <%= end_user.followers.count %>フォロワー
  </div>
  <div class="my_count">
      <%= end_user.followings.count %>フォロー
  </div>
</div>

app/views/admin/end_users/_admin_end_user_sweets_revues.html.erb
<div class = "row ml-3">
    <h5><strong><%= end_user.nickname %>さんの投稿一覧</strong></h5>
</div>

<div class="row mt-4">
  <% sweets_revues.each do |sweets_revue| %>
    <div class="review-box">
        <div class="review_contents_image">
          <%= link_to admin_sweets_revue_path(sweets_revue)  do %>
            <%= image_tag sweets_revue.get_sweets_image(80, 80) %>
          <% end %>
        </div>
        <div class="review_contents_name">
          <%= link_to sweets_revue.sweets_name, admin_sweets_revue_path(sweets_revue.id) %>
          <br><%= sweets_revue.created_at.strftime('%Y/%m/%d') %>
              <% if sweets_revue.post_status == false %>
                <h6 class="text-danger">閲覧制限中</h6>
              <% end %>
        </div>
        <div class="review_contents_star">
          <!--5段階評価 部分テンプレート-->
          <div id="review_star_<#%= sweets_revue.id %>"></div>
          <%= render "public/sweets_revues/review_star", sweets_revue: sweets_revue %>
        </div>
        <div class="review_contents_icon">
          <!--コメント数表示-->
          <i class="far fa-comment fa-2x comment-icon-color"></i><%= sweets_revue.post_comments.count %>
        </div>
        <div class="review_contents_icon">
          <!--いいね数-->
          <i class="far fa-heart fa-2x my_icon-color"></i><%= sweets_revue.favorites.count %>
        </div>
    </div>
  <% end %>
</div>

<div class="d-flex justify-content-center">
  <%= paginate sweets_revues %>
</div>

app/views/admin/end_users/edit.html.erb
<div class="container">
  <!--エラーメッセージ-->
  <%= render "admin/shared/error_messages", resource: @end_user %>

  <div class="row justify-content-center mt-5">
    <h5><strong>会員情報編集</strong></h5>
  </div>

  <div class="row justify-content-center">
    <div class="col-6 text-right">
      <div class="label">会員ID</div>
      <div class="label">名前</div>
      <div class="label">ニックネーム</div>
      <div class="label">メールアドレス</div>
      <div class="label-img">アイコン画像</div>
      <div class="label-intro">自己紹介</div>
      <div class="label">会員ステータス</div>
    </div>

    <div class="col-6 text-left">
      <div class="label"><%= @end_user.id %></div>
      <div class="label"><%= @end_user.name %></div>
      <div class="label"><%= @end_user.nickname %></div>
      <div class="label"><%= @end_user.email %></div>
      <div class="label-img"><%= image_tag @end_user.get_profile_image(100,80) %></div>
      <div class="label-intro"><%= @end_user.introduction %></div>
      <%= form_with model: @end_user, url: admin_end_user_path, method: :patch do |f| %>
        <div class="label-status">
          <div class="is_deleted">
              <%= f.radio_button :is_deleted, false %>
              <%= f.label :is_deleted, '有効'  %>
          </div>
          <div class="is_deleted ml-3">
              <%= f.radio_button :is_deleted, true %>
              <%= f.label :is_deleted, '退会' %>
          </div>
         </div>
        <%= f.submit '変更を保存', class:"btn btn-outline-success mr-4",  data: { confirm: "本当に変更しますか？" } %>
      <% end %>
    </div>
  </dev>

</div>

app/views/admin/end_users/index.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-12">
      <h4 class="text-center mb-3">会員一覧</h4>
    </div>
      <% @end_users.each do |end_user| %>
        <div class="user-box-n p-inherit">
          <div class="user-body"><%= image_tag end_user.get_profile_image(80,80) %></div>
          <div class="user-body"><%= end_user.id %> : <%= link_to end_user.name, admin_end_user_path(end_user) %></div>
          <div class="user-body"><%= end_user.nickname %></div>
          <div class="user-body">投稿<%= end_user.sweets_revues.count %>件</div>
          <div class="user-body"><%= end_user.followers.count %>フォロワー</div>
          <div class="user-body">
            <% if end_user.is_deleted == false %>
              <div class="text-success">有効</div>
            <% else %>
              <div class="text-black-50">退会</div>
            <% end %>
          </div>
        </div>
      <% end %>
  </div>
  <div class="d-flex justify-content-center">
    <%= paginate @end_users %>
  </div>
</div>

app/views/admin/end_users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <!--ユーザー情報部分テンプレート-->
      <%= render "admin_end_user_info", end_user: @end_user %>
    </div>
    <div class="col-8 mt-4">
      <!--投稿部分テンプレート-->
      <%= render 'admin/end_users/admin_end_user_sweets_revues', sweets_revues: @sweets_revues, end_user: @end_user %>
    </div>
  </div>
</div>