config/routes.rb
Rails.application.routes.draw do
## 会員用
# URL /customers/sign_in ...
  devise_for :end_users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

## 管理者用
# URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  devise_scope :end_user do
    ## ゲストログイン用
    post 'end_users/guest_sign_in',to: 'public/sessions#new_guest'
  end


## 会員側ルート設定
  scope module: :public do
    ## homes
    root "homes#top"
    ## sweets_revues
    resources :sweets_revues do
      ## post_comments
      # sweets_revuesに対してコメントされるので親子関係になる
      # ネストしたURLを作成することでparams[:sweets_revue_id]でPostImageのidが取得できるようになる
      resources :post_comments, only: [:create, :destroy]
      ## favorites
      # resource : 単数形にすると、/:idがURLに含まれなくなります
      # 1人のユーザーは1つの投稿に対して1回しかいいねできない」という仕様の為idを含めなくても関連する他のモデルのidから特定できる
      resource :favorites, only: [:create, :destroy]
    end
    ## end_users
    get 'end_users/my_page' => 'end_users#mypage', as: 'mypage'
    # customers/editのようにするとdeviseのルーティングとかぶってしまうためinformationを付け加えている。
    get 'end_users/infomation/:id/edit' => 'end_users#edit', as: 'edit_infomation'
    # patch 'end_users/infomation/:id' => 'end_users#update', as: "update_end_user"
    patch 'end_users/information' => "end_users#update"
    # 退会確認画面
    get 'end_users/confirm'
    # 論理削除用のルーティング
    patch 'end_users/:id/withdraw' => 'end_users#withdraw', as: 'withdraw_end_user'
    resources :end_users, only: [:index, :show] do
      ##relationships
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      # いいね一覧用のルーティング
      # member doを使うとユーザーidが含まれているurlになる
      member do
        get :favorites
      end

    end

  end


 ##管理者側ルート設定
  namespace :admin do
    root "homes#top"
    resources :sweets_revues, only: [:show, :update, :index]
    patch 'sweets_revues/:id/stoppage' => 'sweets_revues#stoppage', as: 'stoppage_sweets_revue'
    resources :end_users, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :update, :destroy]
    resources :tags, only: [:index, :edit, :create, :update, :destroy]

  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_header.html.erb
<li>
  <%= link_to admin_sweets_revues_path, class: "nav-link text-dark" do %>
    <i class="far fa-list-alt"></i>投稿一覧
  <% end %>
</li>
<li>
  <%= link_to admin_end_users_path, class: "nav-link text-dark" do %>
    <i class="fas fa-users"></i>会員一覧
  <% end %>
</li>
<li>
  <%= link_to admin_genres_path, class: "nav-link text-dark" do %>
    <i class="fas fa-cookie-bite"></i>ジャンル項目
  <% end %>
</li>
<li>
  <%= link_to admin_tags_path, class: "nav-link text-dark" do %>
    <i class="fas fa-tags"></i>タグ項目
  <% end %>
</li>
<li>
  <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-dark" do %>
    <i class="fas fa-sign-out-alt"></i>ログアウト
  <% end %>
</li>

app/views/layouts/_end_user_header.html.erb
<li>
  <%= link_to mypage_path, class: "nav-link text-dark" do %>
    <i class="fas fa-user"></i>マイページ
  <% end %>
</li>
<li>
  <%= link_to sweets_revues_path, class: "nav-link text-dark" do %>
    <i class="far fa-list-alt"></i>投稿一覧
  <% end %>
</li>
<li>
  <%= link_to end_users_path, class: "nav-link text-dark" do %>
    <i class="fas fa-users"></i></i>会員一覧
  <% end %>
</li>
<li>
  <%= link_to destroy_end_user_session_path, method: :delete, class: "nav-link text-dark" do %>
    <i class="fas fa-sign-out-alt"></i>ログアウト
  <% end %>
</li>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= obj.errors.count %> 件のエラーが発生しました。</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_sweets_revues.html.erb
<div class = "row ml-3">
    <h5><strong><%= end_user.nickname %>さんの投稿一覧</strong></h5>
</div>

<div class="row">
  <table>
    <tbody>
      <% sweets_revues.each do |sweets_revue| %>
        <tr>
          <td>
            <%= link_to sweets_revue_path(sweets_revue)  do %>
              <%= image_tag sweets_revue.get_sweets_image(100, 80) %>
            <% end %>
          </td>
          <td>
            <%= link_to sweets_revue.sweets_name, sweets_revue_path(sweets_revue.id) %>
            <br><%= sweets_revue.created_at.strftime('%Y/%m/%d') %>
          </td>
          <td>
            <!--5段階評価 部分テンプレート-->
            <div id="review_star_<#%= sweets_revue.id %>"></div>
            <%= render "public/sweets_revues/review_star", sweets_revue: sweets_revue %>
          </td>
          <td>
            <!--コメント数表示-->
            <i class="far fa-comment fa-2x"></i><%= sweets_revue.post_comments.count %>
          </td>
          <td>
          <!--いいね機能部分テンプレート-->
          <%= render 'public/sweets_revues/favorite', sweets_revue: sweets_revue %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="text-center mt-3">
  <%= paginate sweets_revues %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SweetsHiyori</title>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1">-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body class="d-flex flex-column">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light" style ="background-color: lemonchiffon">
        <div class="container">
          <% if admin_signed_in? %>
            <a class="navbar-brand p-3"><%= link_to 'Sweets日和', admin_root_path, class: "link" %></a>
          <% else %>
            <a class="navbar-brand p-3"><%= link_to 'Sweets日和', root_path, class: "link" %></a>
          <% end %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if end_user_signed_in? %>
                <%= render 'layouts/end_user_header' %>
              <% elsif admin_signed_in? %>
                <%= render 'layouts/admin_header' %>
              <% else %>
                <li>
                  <%= link_to new_end_user_registration_path, class: "nav-link text-dark" do %>
                    <i class="fas fa-user-plus"></i>新規登録
                <% end %>
                </li>
                <li>
                  <%= link_to new_end_user_session_path, class: "nav-link text-dark" do %>
                    <i class="fas fa-sign-in-alt"></i>ログイン
                  <% end %>
                </li>
                <li>
                  <%= link_to sweets_revues_path, class: "nav-link text-dark" do %>
                    <i class="far fa-list-alt"></i>投稿一覧
                  <% end %>
                </li>
                <li>
                  <%= link_to end_users_guest_sign_in_path, class: "nav-link text-dark", method: :post do %>
                    <i class="fas fa-sign-in-alt"></i>ゲストログイン
                  <% end %>
                </li>
                <li>
                  <%= link_to admin_session_path, class: "nav-link text-dark" do %>
                  .
                  <% end %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <p id = "notice"><%= notice %></p>
      <div class="end_user_name">
        <% if end_user_signed_in? %>
          <h6 style="color:#b0c4de"><%= current_end_user.name %>さんログイン中</h6>
        <% end %>
      </div>
      <div class="main_body mb-5">
            <%= yield %>
      </div>
    </main>

    <footer>
      <div class="fixed-bottom text-center" style ="background-color: lemonchiffon">
        <p>© 2022 Sanple Name</p>
      </div>
    </footer>
  </body>
</html>